### PR TITLE
Add translation option

### PR DESCRIPTION
**Pull request by texnixe**
Adds translation for select options and possibility to define user defined translations via the config.php file.

### CODE REVIEW

**Comment by jenstornell** [comment]
Thanks for your commit!

I'm still behind my schedule, so I did not have time to test it out, but I trust you, so I merged it anyway.

Lang support is a nice feature.

So I hope it works! =)

**Comment by texnixe** [comment]
Oh, that's adventurous 😜 ...

**Comment by ghost** [comment]
I've tested committed code and it works as intended. 👍 Great work @texnixe.

**Comment by texnixe** [comment]
@mikewink Thanks for your feedback 🙂

**Comment by jenstornell** [comment]
@texnixe @mikewink 

It's awesome how plugins can just update and test themselves like that. 😄 

Thank you both!

**Pull request merged**
